name: tfl-nexus-v2

services:
  tfl-nexus-api:
    build: .
    image: tfl-nexus-v2
    ports:
      - "9000:9000"
    volumes:
      - ./src/tfl_nexus.db:/app/tfl_nexus.db:rw
    env_file:
      - src/.env

  tfl-nexus-db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "tfl", "-d", "tfl_nexus"]
      interval: 1m
      timeout: 5s
      retries: 5